### PR TITLE
rt-bug-dotFiles

### PR DESCRIPTION
**Pull request by MrT3313**
All of the `dot` files were not correctly copied over from the base labs repo. 

I made a fresh clone from the base repo (https://github.com/Lambda-School-Labs/xcel-wom-api), emptied the existing repo, cloned the fresh version into the existing repo, and then updated the remote origin.

### CODE REVIEW

**Review by aricrepp — APPROVED** [review]
Looks good to me

**Review by luanvu1711 — COMMENTED** [review]
Reviewed. All set

**Review by sophiasagan — CHANGES_REQUESTED** [review]
Failing tests. Linter issue. Can we get this corrected before merging?

**Review by aricrepp — APPROVED** [review]
Error fixed, tests passing

**Review by luanvu1711 — APPROVED** [review]
Error fixed

**Review by sophiasagan — APPROVED** [review]
Passing tests now. All other changes look good.

**Review by germainep — APPROVED** [review]
After you fixed the error in profileRouter every thing looks good and the linter passed

**Review by sophiasagan — APPROVED** [review]

**Review by tommyconner96 — APPROVED** [review]

**Pull request merged**
